package il.ac.shenkar.hibernate.model;

import il.ac.shenkar.hibernate.model.dao.ToiListException;
import javax.persistence.*;

/**
 * This class is used to instantiate and manipulate objects that represent items in a list
 * @author Arel Gindos
 * @author Dassi Rosen
 * @author Lior Lerner
*/
@SuppressWarnings("ALL")
@Table(name = "ITEMS")
public class Item {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    private int id;
    @Column(name = "USERID")
    private int userId;
    @Column(name = "TITLE")
    private String title;
    @Column(name = "STATUS")
    private String status;

    /**
     * Default Constructor
    */
    public Item() {
    }
    
    /**
     * Constructor
     * @param userId id of the user that created the item
     * @param title the desired title
     * @param status current status
     * @throws ToiListException
    */
    public Item(int userId, String title, String status) throws ToiListException {
        setUserId(userId);
        setTitle(title);
        setStatus(status);
    }

    /**
     * Returns item id
     * @return the desired item id
    */
    public int getId() {
        return id;
    }

    /**
     * Sets item id
     * @param id unique autogenerated item id
    */
    public void setId(int id) {this.id = id;}

    /**
     * Returns user id of the user associated with an item 
     * @return the desired user id
    */
    public int getUserId() {
        return userId;
    }

    /**
     * Associates item with user
     * @param userId desired user to associate with item
    */
    private void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * Returns item title
     * @return desired item name
    */
    public String getTitle() {
        return title;
    }

    /**
     * Sets item title
     * @param itemName desired item name
    */
    public void setTitle(String itemName) {
        this.title = itemName;
    }

    /**
     * Returns item status
     * @return desired item status
    */
    public String getStatus() {
        return status;
    }

    /**
     * Sets item status
     * @param itemStatus desired item status
    */
    public void setStatus(String itemStatus) {
        this.status = itemStatus;
    }
    
    @Override
    public String toString() {
        return "Item [itemId=" + getId() + ", userId=" + getUserId() + ", itemName=" + getTitle() + ", status=" + getStatus() + "]";
    }
}
